server:
  port: 8080
  servlet:
    context-path: /acm
spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/ace?allowMultiQueries=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 
    password: 
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    check-template: true
    suffix: .html
    mode: HTML
    cache: false
cloud4u:
  token:
    expire:
      day: 1
      hour: 1
      min: 10
    subject: 
    issuer: 
  acm:
    base-package: 
    key-limit: 100
    aid: 
    token: 
    verify: 
    